on: pull_request_target
jobs:  
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to comment hello
    steps:
    - name: Hello world action step
      id: hello
      uses: HarishTeens/hacktoberfest-greet@v1.1.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}